const PDFDocument = require("pdfkit");

/**
 * Generates a professional PDF stream for the compliance report.
 * @param {Object} data - The full data object (product info + compliance report)
 * @returns {PDFDocument} - The readable PDF stream
 */
function generatePDFReport(data) {
  const doc = new PDFDocument({ margin: 50, size: "A4" });
  const report = data.compliance_report;

  // Colors
  const COLOR_PRIMARY = "#1A5276"; // Deep Blue
  const COLOR_DANGER = "#C0392B"; // Dark Red
  const COLOR_WARNING = "#F39C12"; // Orange
  const COLOR_SUCCESS = "#27AE60"; // Green
  const COLOR_GREY = "#ECF0F1"; // Light Grey

  // --- 1. HEADER STRIP ---
  doc.rect(0, 0, 595.28, 80).fill(COLOR_PRIMARY);
  doc.fontSize(24).fillColor("white").text("COMPLIANCE CERTIFICATE", 50, 25);
  doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`, 50, 55);
  doc.text(`Report ID: ${Date.now()}`, 400, 55, { align: "right" });

  // Reset text color
  doc.fillColor("black");
  doc.moveDown(4);

  // --- 2. PRODUCT INFO BOX ---
  const boxTop = 110;
  doc.roundedRect(50, boxTop, 495, 90, 5).strokeColor("#BDC3C7").stroke();

  doc
    .fontSize(10)
    .fillColor("#7F8C8D")
    .text("PRODUCT DETAILS", 65, boxTop + 10);
  doc
    .fontSize(14)
    .fillColor("black")
    .font("Helvetica-Bold")
    .text(data.product, 65, boxTop + 25);

  doc
    .fontSize(10)
    .font("Helvetica")
    .fillColor("#7F8C8D")
    .text("CATEGORY", 65, boxTop + 50);
  doc
    .fontSize(12)
    .fillColor("black")
    .text(data.category.toUpperCase(), 65, boxTop + 62);

  doc
    .fontSize(10)
    .fillColor("#7F8C8D")
    .text("STANDARD", 250, boxTop + 50);
  doc
    .fontSize(12)
    .fillColor("black")
    .text(report.standard, 250, boxTop + 62);

  // --- 3. RISK SCORE BADGE ---
  const scoreColor = report.risk_score >= 50 ? COLOR_DANGER : COLOR_SUCCESS;

  doc.circle(480, boxTop + 45, 35).fill(scoreColor);
  doc
    .fontSize(18)
    .fillColor("white")
    .font("Helvetica-Bold")
    .text(report.risk_score, 462, boxTop + 32);
  doc.fontSize(8).text("RISK SCORE", 458, boxTop + 52);

  doc
    .fontSize(10)
    .fillColor(scoreColor)
    .text(report.risk_level, 400, boxTop + 95, { width: 160, align: "center" });

  // --- 4. AI SUMMARY SECTION (CLEANED) ---
  doc.moveDown(5);
  const summaryTop = 230;

  // Header Bar
  doc.rect(50, summaryTop, 495, 25).fill(COLOR_GREY);
  doc
    .fontSize(12)
    .fillColor("#2C3E50")
    .font("Helvetica-Bold")
    .text("AI EXECUTIVE SUMMARY", 60, summaryTop + 7);

  // TEXT SANITIZER
  let cleanSummary = (report.ai_explanation || "No summary available.")
    .replace(/\*\*/g, "") // Remove bold markers (**)
    .replace(/\*/g, "•") // Replace single asterisk with bullet dot
    .replace(/•\s/g, "\n• ") // Ensure bullets start on new lines
    .replace(/\n\n/g, "\n"); // Remove double spacing

  doc
    .fontSize(10)
    .font("Helvetica")
    .fillColor("#34495E")
    .text(cleanSummary, 50, summaryTop + 35, {
      align: "justify",
      width: 495,
      lineGap: 4,
    });

  // --- 5. VIOLATIONS TABLE ---
  // We need to calculate where the table starts dynamically based on text length
  const summaryHeight = doc.heightOfString(cleanSummary, { width: 495, lineGap: 4 });
  let tableTop = summaryTop + 35 + summaryHeight + 20;

  if (report.violations.length > 0) {
    // Table Header
    doc.rect(50, tableTop, 495, 20).fill("#34495E");
    doc.fontSize(10).fillColor("white").font("Helvetica-Bold");
    doc.text("REGULATION RULE", 60, tableTop + 6);
    doc.text("LIMIT", 260, tableTop + 6);
    doc.text("ACTUAL", 340, tableTop + 6);
    doc.text("SEVERITY", 425, tableTop + 6);

    // Table Rows
    let y = tableTop + 25;
    doc.font("Helvetica");

    report.violations.forEach((v, i) => {
      // Alternating Row Background
      if (i % 2 === 0) {
        doc.rect(50, y - 5, 495, 25).fill("#F8F9F9");
      }

      doc.fillColor("black").fontSize(10);
      doc.text(v.rule_name, 60, y, { width: 190 });
      doc.text(v.limit_readable, 260, y);
      doc.text(v.actual_percent, 340, y);

      const badgeColor =
        v.severity === "CRITICAL" ? COLOR_DANGER : COLOR_WARNING;
      doc.roundedRect(420, y - 3, 80, 15, 6).fill(badgeColor);
      doc
        .fillColor("white")
        .fontSize(8)
        .font("Helvetica-Bold")
        .text(v.severity, 420, y+1, { width: 80, align: "center", lineBreak: false });

      y += 25;

      // Page Break Check
      if (y > 750) {
        doc.addPage();
        y = 50;
      }
    });
  }

  // --- FOOTER ---
  const bottom = doc.page.height - 50;
  doc.moveTo(50, bottom).lineTo(545, bottom).strokeColor("#BDC3C7").stroke();
  doc
    .fontSize(8)
    .fillColor("#7F8C8D")
    .text(
      "Generated by Automated Compliance Engine (ACE) v1.0 | Bureau of Indian Standards Aligned",
      50,
      bottom + 10,
      { align: "center" },
    );

  doc.end();
  return doc;
}

module.exports = { generatePDFReport };
